image: node:16-alpine

before_script:  
  - apk add --no-cache git
  - yarn install --frozen-lockfile
  - cp .env.example .env

stages:
  - lint
  - test

lint:
  dependencies: []
  stage: lint
  script:
    - yarn lint:check
  allow_failure: true # FIXME re-enable when all linting errors are fixed
  rules:
    - when: always
  tags:
    - web-test

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

test:
  dependencies: []
  stage: test
  script:
    - yarn compile
    - yarn test
  rules:
    - when: always
  tags:
    - web-test
